services:
  zeebe:
    image: camunda/zeebe:8.2.12
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME: io.camunda.zeebe.exporter.ElasticsearchExporter
      ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      xpack.security.enabled: 'false'
      cluster.routing.allocation.disk.threshold_enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 30s
      timeout: 5s
      retries: 3
