services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:21.1
    ports:
      - "8180:8080"
    volumes:
      - ./docker/keycloak/provisioning:/opt/keycloak/data/import
    command: |
      start-dev
      --import-realm
    environment:
      KC_HOSTNAME_STRICT: 'false'
      KEYCLOAK_ADMIN: landlord
      KEYCLOAK_ADMIN_PASSWORD: Prop3r7y

  codimd-server:
    depends_on:
      - codimd-database
      - keycloak-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CMD_ALLOW_ANONYMOUS: 'false'
      CMD_OAUTH2_PROVIDERNAME: Keycloak
      CMD_OAUTH2_BASEURL: http://host.docker.internal:8180/realms/playground
      CMD_OAUTH2_CLIENT_ID: codimd
      CMD_OAUTH2_CLIENT_SECRET: 0iGI3mWUwoBZAZpzEuGjAj0jJzt6YPSo
      CMD_OAUTH2_SCOPE: openid
      CMD_OAUTH2_AUTHORIZATION_URL: http://host.docker.internal:8180/realms/playground/protocol/openid-connect/auth
      CMD_OAUTH2_TOKEN_URL: http://host.docker.internal:8180/realms/playground/protocol/openid-connect/token
      CMD_OAUTH2_USER_PROFILE_URL: http://host.docker.internal:8180/realms/playground/protocol/openid-connect/userinfo
      CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR: preferred_username
      CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR: name
      CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR: email
