services:
  preview-service:
    image: vinado/preview-service:0.4.1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  keycloak-server:
    image: quay.io/keycloak/keycloak:21.1
    ports:
      - "8180:8080"
    volumes:
      - ./docker/keycloak/provisioning:/opt/keycloak/data/import
    command: |
      start-dev
      --import-realm
    environment:
      KEYCLOAK_ADMIN: landlord
      KEYCLOAK_ADMIN_PASSWORD: Prop3r7y
