services:
  preview-service:
    image: vinado/preview-service:0.4.1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  codimd-server:
    depends_on:
      - codimd-database
    image: hackmdio/hackmd:2.4.2
    ports:
      - "8280:3000"
    environment:
      CMD_USECDN: "false"
      CMD_AUTO_VERSION_CHECK: "false"
      CMD_DB_URL: postgres://postgres:BTton2dQ4o9-8m_s@codimd-database/postgres
      CMD_ALLOW_ANONYMOUS: "true"
      CMD_DEFAULT_PERMISSION: limited
      CMD_SESSION_SECRET: XWnPHmfLF7zRPTXVZUPF95_h
      CMD_ALLOW_FREEURL: "true"
      CMD_IMAGE_UPLOAD_TYPE: filesystem
      CMD_EMAIL: "false"
      CMD_HSTS_ENABLE: "false"
      CMD_CSP_ENABLE: "false"

  codimd-database:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_PASSWORD: BTton2dQ4o9-8m_s
