services:
  operate:
    image: camunda/operate:8.2.12
    ports:
      - "8382:8080"
    environment:
      CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS: zeebe:26500
      CAMUNDA_OPERATE_ELASTICSEARCH_URL: http://elasticsearch:9200
      CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch
