spring:
  docker:
    compose:
      file:
        - compose.yaml
        - compose.keycloak.yaml

  security.oauth2:
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8180/realms/local
          user-name-attribute: preferred_username
      registration:
        keycloak:
          client-name: Keycloak
          client-id: playground
          client-secret: etgWLsvbyKRdxFXIyeZpWbor99sKjQ42
          authorization-grant-type: authorization_code
          scope: openid
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8180/realms/local

app:
  security.oauth2.client:
    post-logout-redirect-uri: http://localhost:8080${server.servlet.context-path:/}
    registration:
      keycloak:
        roles-json-path: $.resource_access.playground.roles[*]
