spring:
  main.banner-mode: "off"
  profiles:
    default: wicket,keycloak
    group:
      keycloak: oauth2

app:
  wicket:
    runtime-configuration: DEPLOYMENT

  document:
    preview:
      base-url: http://localhost:3000

  note:
    codimd:
      base-url: http://localhost:8280
