spring:
  main.banner-mode: "off"
  profiles:
    default: wicket
    group:
      keycloak: oauth2

  docker.compose:
    lifecycle-management: start_only
    start:
      skip: never
      log-level: debug

app:
  wicket:
    runtime-configuration: development

  document:
    preview:
      base-url: http://localhost:3000

  note:
    codimd:
      base-url: http://localhost:8280
